# Generated by Django 5.2.4 on 2025-08-13 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chw_cases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='district',
            field=models.TextField(blank=True),
        ),
    ]
