# Generated by Django 5.2.4 on 2025-09-03 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chw_cases', '0002_case_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='encounter_location',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='case',
            name='follow_up_required',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='case',
            name='housing_type',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='case',
            name='number_of_dependents',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='reporting_method',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='case',
            name='visit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='visit_type',
            field=models.TextField(blank=True),
        ),
    ]
