# Generated by Django 5.2.4 on 2025-09-21 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chw_cases', '0003_case_encounter_location_case_follow_up_required_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='classification',
            field=models.TextField(blank=True),
        ),
    ]
