# Generated by Django 5.2.4 on 2025-09-03 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hso_cases', '0002_case_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='case_source',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='case',
            name='contact_tracing_done',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='case',
            name='environmental_risk_factors',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='case',
            name='population_estimate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='reporting_method',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='case',
            name='supervising_facility',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='case',
            name='vector_control_measure',
            field=models.TextField(blank=True),
        ),
    ]
