# Generated by Django 5.2.4 on 2025-09-03 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_cases', '0002_case_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='admission_status',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='case',
            name='discharge_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='case',
            name='follow_up_plan',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='case',
            name='lab_results_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='case',
            name='lab_tests_ordered',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='case',
            name='physical_exam_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='case',
            name='procedures_done',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='case',
            name='referral_facility',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='case',
            name='triage_level',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='case',
            name='vital_signs',
            field=models.TextField(blank=True),
        ),
    ]
